# Generated by Django 3.2.4 on 2021-08-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField(verbose_name='Nombre del curso')),
                ('duracion', models.TextField(max_length=12, verbose_name='Duracion del curso')),
                ('carrera', models.TextField()),
                ('horario', models.CharField(max_length=10, verbose_name='Turno del curso')),
                ('nombre', models.TextField(verbose_name='Instructor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
    ]
