# Generated by Django 3.2.4 on 2021-08-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_comentariocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('mate', models.TextField(verbose_name='Curso')),
                ('turno', models.TextField(verbose_name='Turno')),
                ('carrera', models.TextField(verbose_name='Carrera')),
                ('instructor', models.TextField(verbose_name='Instructor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario Curso',
                'verbose_name_plural': 'Comentarios Cursos',
                'ordering': ['-created'],
            },
        ),
    ]
